matrix:
  include:

    - language: java
      jdk: oraclejdk8
      script: ./gradlew build

    - language: node_js
      node_js:
        - "11.11.0"
      before_script:
        - cd grocery-client
        - export NG_CLI_ANALYTICS=ci
        - npm i -g npm@latest
        - npm install -g @angular/cli@8.0.0
        - npm install

      script:
        - ng build --prod

cache:
  directories:
  - $HOME/.gradle
  - node_modules